export const APP_CATEGORIES = [
  "Web Application",
  "Mobile Application",
  "Desktop Application",
  "Browser Extension",
  "API/Backend Service",
  "Developer Tool",
  "Game",
  "Educational",
  "Business/Productivity",
  "Social/Communication",
  "Entertainment",
  "Other",
] as const;

export const TECH_STACK_OPTIONS = {
  frontend: [
    "React",
    "Vue.js",
    "Angular",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Gatsby",
    "Remix",
    "Astro",
    "SolidJS",
    "Alpine.js",
    "jQuery",
    "Vanilla JS",
    "TypeScript",
    "JavaScript",
  ],
  backend: [
    "Node.js",
    "Express.js",
    "NestJS",
    "Python",
    "Django",
    "Flask",
    "FastAPI",
    "Ruby",
    "Ruby on Rails",
    "Go",
    "Gin",
    "Echo",
    "Java",
    "Spring Boot",
    "PHP",
    "Laravel",
    "Symfony",
    "C#",
    ".NET Core",
    "Rust",
    "Actix",
    "Elixir",
    "Phoenix",
  ],
  database: [
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "SQLite",
    "MariaDB",
    "Oracle",
    "SQL Server",
    "Cassandra",
    "DynamoDB",
    "Firestore",
    "Supabase",
    "PlanetScale",
    "CockroachDB",
    "Neo4j",
    "Elasticsearch",
  ],
  cloud: [
    "AWS",
    "Google Cloud",
    "Azure",
    "Vercel",
    "Netlify",
    "Heroku",
    "DigitalOcean",
    "Cloudflare",
    "Railway",
    "Render",
    "Fly.io",
    "Linode",
    "Oracle Cloud",
    "IBM Cloud",
  ],
  mobile: [
    "React Native",
    "Flutter",
    "Swift",
    "SwiftUI",
    "Kotlin",
    "Jetpack Compose",
    "Ionic",
    "Xamarin",
    "NativeScript",
    "Expo",
  ],
  tools: [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "GitHub Actions",
    "CircleCI",
    "Travis CI",
    "Webpack",
    "Vite",
    "Rollup",
    "Parcel",
    "ESLint",
    "Prettier",
    "Jest",
    "Cypress",
    "Playwright",
  ],
} as const;

export const PLATFORM_OPTIONS = [
  "Web",
  "iOS",
  "Android",
  "Windows",
  "macOS",
  "Linux",
  "Chrome Extension",
  "Firefox Extension",
  "Safari Extension",
  "Edge Extension",
  "Progressive Web App",
  "Cross-Platform Desktop",
] as const;

export const LICENSE_OPTIONS = [
  "MIT",
  "Apache 2.0",
  "GPL v3",
  "BSD 3-Clause",
  "BSD 2-Clause",
  "ISC",
  "LGPL v3",
  "AGPL v3",
  "Unlicense",
  "Creative Commons Zero",
  "Creative Commons BY",
  "Creative Commons BY-SA",
  "Creative Commons BY-NC",
  "Creative Commons BY-NC-SA",
  "Proprietary",
  "Other",
] as const;

export const APP_STATUS = {
  DRAFT: "draft",
  SUBMITTED: "submitted",
  IN_REVIEW: "in-review",
  APPROVED: "approved",
  REJECTED: "rejected",
  DELETED: "deleted",
} as const;

export const APP_STATUS_LABELS = {
  [APP_STATUS.DRAFT]: "Draft",
  [APP_STATUS.SUBMITTED]: "Submitted",
  [APP_STATUS.IN_REVIEW]: "In Review",
  [APP_STATUS.APPROVED]: "Approved",
  [APP_STATUS.REJECTED]: "Rejected",
  [APP_STATUS.DELETED]: "Deleted",
} as const;

export const APP_STATUS_COLORS = {
  [APP_STATUS.DRAFT]: "gray",
  [APP_STATUS.SUBMITTED]: "blue",
  [APP_STATUS.IN_REVIEW]: "yellow",
  [APP_STATUS.APPROVED]: "green",
  [APP_STATUS.REJECTED]: "red",
  [APP_STATUS.DELETED]: "gray",
} as const;

// Validation constants
export const APP_VALIDATION = {
  name: {
    min: 3,
    max: 50,
    pattern: /^[a-zA-Z0-9\s\-\.]+$/,
    message: "App name must be 3-50 characters, alphanumeric, spaces, hyphens, and dots only",
  },
  shortDescription: {
    min: 10,
    max: 160,
    message: "Short description must be 10-160 characters",
  },
  fullDescription: {
    min: 50,
    max: 2000,
    message: "Full description must be 50-2000 characters",
  },
  tags: {
    max: 5,
    message: "Maximum 5 tags allowed",
  },
  screenshots: {
    min: 2,
    max: 6,
    message: "At least 2 screenshots required, maximum 6",
  },
  icon: {
    maxSize: 2 * 1024 * 1024, // 2MB
    minDimensions: { width: 512, height: 512 },
    formats: ["image/png", "image/jpeg", "image/webp"],
    message: "Icon must be at least 512x512px, max 2MB, PNG/JPG/WebP",
  },
  screenshot: {
    maxSize: 5 * 1024 * 1024, // 5MB
    minDimensions: { width: 1280, height: 720 },
    formats: ["image/png", "image/jpeg", "image/webp"],
    message: "Screenshots must be at least 1280x720px, max 5MB each, PNG/JPG/WebP",
  },
} as const;