export const GUIDE_CATEGORIES = [
  { value: 'getting-started', label: 'Getting Started' },
  { value: 'tutorials', label: 'Tutorials' },
  { value: 'how-to', label: 'How-To Guides' },
  { value: 'best-practices', label: 'Best Practices' },
  { value: 'architecture', label: 'Architecture & Design' },
  { value: 'performance', label: 'Performance' },
  { value: 'security', label: 'Security' },
  { value: 'testing', label: 'Testing' },
  { value: 'devops', label: 'DevOps' },
  { value: 'career', label: 'Career Development' },
  { value: 'project-showcases', label: 'Project Showcases' },
  { value: 'tips-tricks', label: 'Tips & Tricks' },
] as const;

export const DIFFICULTY_LEVELS = [
  { value: 'beginner', label: 'Beginner', color: 'text-green-600' },
  { value: 'intermediate', label: 'Intermediate', color: 'text-yellow-600' },
  { value: 'advanced', label: 'Advanced', color: 'text-red-600' },
] as const;

export const GUIDE_STATUS = {
  DRAFT: 'draft',
  PUBLISHED: 'published',
  UNPUBLISHED: 'unpublished',
} as const;

export const PROGRAMMING_LANGUAGES = [
  'javascript',
  'typescript',
  'python',
  'java',
  'csharp',
  'cpp',
  'c',
  'go',
  'rust',
  'swift',
  'kotlin',
  'ruby',
  'php',
  'scala',
  'dart',
  'r',
  'matlab',
  'bash',
  'powershell',
  'sql',
  'html',
  'css',
  'sass',
  'less',
  'json',
  'yaml',
  'xml',
  'markdown',
  'dockerfile',
  'makefile',
] as const;

export const GUIDE_TAGS = [
  'react',
  'nextjs',
  'vue',
  'angular',
  'svelte',
  'nodejs',
  'express',
  'fastify',
  'nestjs',
  'mongodb',
  'postgresql',
  'mysql',
  'redis',
  'docker',
  'kubernetes',
  'aws',
  'azure',
  'gcp',
  'vercel',
  'netlify',
  'git',
  'github',
  'gitlab',
  'testing',
  'jest',
  'cypress',
  'playwright',
  'webpack',
  'vite',
  'rollup',
  'babel',
  'eslint',
  'prettier',
  'tailwindcss',
  'sass',
  'styled-components',
  'material-ui',
  'chakra-ui',
  'graphql',
  'rest-api',
  'websockets',
  'authentication',
  'authorization',
  'security',
  'performance',
  'seo',
  'accessibility',
  'mobile',
  'desktop',
  'cli',
  'debugging',
  'deployment',
  'ci-cd',
  'monitoring',
  'logging',
] as const;